document.write("<p>Version: ");
document.write(navigator.appVersion);
document.write("</p>");
document.write("<p>Plataforma: ");
document.write(navigator.platform);
document.write("</p>");
document.write("<p>Vendedor: ");
document.write(navigator.vendor);
document.write("</p>");
document.write("<p>Agente: ");
document.write(navigator.userAgent);
document.write("</p>");
document.write("<p>Java activo: ");
document.write(navigator.javaEnabled());
document.write("</p>");